# Site settings
title: Sam's Blog
description: A blog - a blog for sam in fact.
keywords: Sam, blog, internet, nerd, programming, motorcycle, gaming
author: Sam
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://blog.sampeters.net" # the base hostname & protocol for your site
gems:
  - octopress-debugger
exclude: [vendor, 'config.ru', 'Gemfile', 'Gemfile.lock']